# Generated by Django 4.0.4 on 2022-06-16 20:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "experience_level",
                    models.CharField(
                        choices=[
                            ("Learning", "Leaning"),
                            ("Trained", "Trained"),
                            ("Experienced", "Experienced"),
                            ("Supervisory", "Supervisory"),
                        ],
                        max_length=11,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("poster", models.EmailField(max_length=100)),
                ("hours_per_week", models.PositiveSmallIntegerField()),
                ("num_positions_available", models.PositiveSmallIntegerField()),
                ("posted_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "opportunity",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.SlugField(max_length=100)),
                ("description", models.TextField()),
            ],
            options={
                "db_table": "project",
            },
        ),
        migrations.CreateModel(
            name="RecurringEvent",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.SlugField(max_length=100)),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Sunday", "Sunday"),
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                        ],
                        max_length=9,
                    ),
                ),
                ("start_time", models.TimeField()),
                ("duration_in_minutes", models.PositiveSmallIntegerField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recurring_events",
                        to="server.project",
                    ),
                ),
            ],
            options={
                "db_table": "recurring_event",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.SlugField(max_length=100)),
            ],
            options={
                "db_table": "role",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.SlugField(max_length=100)),
            ],
            options={
                "db_table": "skill",
            },
        ),
        migrations.CreateModel(
            name="RoleXRecurringEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recurring_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server.recurringevent",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.role"
                    ),
                ),
            ],
            options={
                "db_table": "role__recurring_event",
                "unique_together": {("role", "recurring_event")},
            },
        ),
        migrations.AddField(
            model_name="recurringevent",
            name="roles",
            field=models.ManyToManyField(
                blank=True, through="server.RoleXRecurringEvent", to="server.role"
            ),
        ),
        migrations.CreateModel(
            name="OpportunityXSkill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_required", models.BooleanField(blank=True, null=True)),
                (
                    "opportunity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opp_to_skill",
                        to="server.opportunity",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.skill"
                    ),
                ),
            ],
            options={
                "db_table": "opportunity__skill",
                "unique_together": {("opportunity", "skill")},
            },
        ),
        migrations.AddField(
            model_name="opportunity",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="server.project"
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="server.role"
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="skills",
            field=models.ManyToManyField(
                blank=True, through="server.OpportunityXSkill", to="server.skill"
            ),
        ),
    ]
