# Generated by Django 4.0.7 on 2022-10-23 20:13

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExperienceLevel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "experience_level",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("github_url", models.URLField()),
                ("slack_url", models.URLField()),
                ("google_drive_url", models.URLField()),
                ("video_conference_link", models.URLField()),
                ("project_status", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "project",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "role",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "skill",
            },
        ),
        migrations.CreateModel(
            name="RecurringEvent",
            fields=[
                (
                    "id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("hours", models.FloatField()),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.project"
                    ),
                ),
                ("roles", models.ManyToManyField(to="server.role")),
            ],
            options={
                "db_table": "recurring_event",
            },
        ),
        migrations.CreateModel(
            name="Opportunity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("poster", models.EmailField(max_length=100)),
                ("hours_per_week", models.PositiveSmallIntegerField()),
                ("num_positions_available", models.PositiveSmallIntegerField()),
                ("posted_date", models.DateField(auto_now_add=True)),
                (
                    "experience_level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="server.experiencelevel",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.project"
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="server.role"
                    ),
                ),
                ("skills", models.ManyToManyField(blank=True, to="server.skill")),
            ],
            options={
                "db_table": "opportunity",
            },
        ),
    ]
