# Generated by Django 4.0.10 on 2023-04-02 06:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpportunityXMeetings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('meeting_id', models.IntegerField(unique=True)),
                ('meeting_type', models.PositiveSmallIntegerField(choices=[(0, 'Not Attend'), (1, 'Could Attend'), (2, 'Should Attend')])),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityXTech',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tech_type', models.PositiveSmallIntegerField(choices=[(0, 'Preferred'), (1, 'Required')])),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='opportunityxskill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='opportunityxskill',
            name='opportunity',
        ),
        migrations.RemoveField(
            model_name='opportunityxskill',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='recurringevent',
            name='project',
        ),
        migrations.RemoveField(
            model_name='recurringevent',
            name='roles',
        ),
        migrations.AlterUniqueTogether(
            name='rolexrecurringevent',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rolexrecurringevent',
            name='recurring_event',
        ),
        migrations.RemoveField(
            model_name='rolexrecurringevent',
            name='role',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='hours_per_week',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='num_positions_available',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='project',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='role',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='title',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='experience_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='Experience Level ID'),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='is_active',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='is_remote',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='max_commitment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='max_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='min_commitment',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='min_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='project_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='role_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='posted_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.DeleteModel(
            name='OpportunityXSkill',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='RecurringEvent',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.DeleteModel(
            name='RoleXRecurringEvent',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='opportunityxtech',
            name='opportunity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.opportunity'),
        ),
        migrations.AddField(
            model_name='opportunityxmeetings',
            name='opportunity_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.opportunity'),
        ),
    ]
