# Generated by Django 6.0.4 on 2026-06-18 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='meeting_availability',
            field=models.JSONField(blank=True, help_text='Availability windows the user can attend. JSON shape: [{"day": "Wed", "start": "17:00", "end": "21:00"}, ...]', null=True),
        ),
    ]
