default_language_version:
  # default language version for each language used in the repository
  python: python3.9
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      # See https://pre-commit.com/hooks.html for more hooks
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
      - id: name-tests-test
        args: ["--django"]
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--settings-file", "app/setup.cfg"]
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args: []
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--config", "app/setup.cfg"]
        additional_dependencies:
          [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
          ]
  - repo: https://github.com/pycqa/pylint
    rev: "v2.15.10"
    hooks:
      - id: pylint
        exclude: "[a-zA-Z]*/(migrations)/(.)*|(mkdocs)/(.)*"
        args:
          [
            "--load-plugins=pylint_django",
            "--disable=C0114,C0115,C0116",
            "--django-settings-module=config.settings",
            "--rcfile=app/setup.cfg",
          ]
        additional_dependencies: [django, djangorestframework, pylint_django]
