version: "3.8"

services:
  pgdb:
    image: postgres
    container_name: pgdb
    volumes:
      - postgres_data:/lib/postgresql/data
    env_file:
      - ./stage/stage.env

  django:
    build: 
      context: ./app
      dockerfile: ../stage/Dockerfile
    container_name: django
    ports:
      - "8000:8000"
    env_file:
      - ./stage/stage.env
    depends_on:
      - pgdb

volumes:
  postgres_data:
