name: "Blank Issue Form (w/ Dependency)"
description: "Form version of HackforLA blank issue template with dependency"
labels: ["Dependency"]

body:
  - type: textarea
    id: dependency-explanation
    attributes:
      label: Dependency
      description: If there is a dependency, please explain what it is.
      placeholder: |
        - [ ] Dependency 1
    validations:
      required: true
  - type: textarea
    id: overview
    attributes:
      label: Overview
      description: Clearly state the purpose of this issue in 2 sentences or less
      placeholder: |
        Example: As a [developer/programmer/designer/member of the team/etc], we need to [insert some sort of standard, such as "keep out code clean" or "fix bugs" or "make sure website appears welcoming"]. For this issue, we will [do something to fulfill our standard, such as "edit the code in the data folder" or "correct a bug in out components" or "increase the title size on the homepage"].
    validations:
      required: true
  - type: textarea
    id: action-items
    attributes:
      label: Action Items
      description: "List the research to be done, or the steps to be completed. Note: If the steps can be divided into tasks for more than one person, we recommend dividing it up into separate issues, or assigning it as a pair programming task."
      value: |
        - [ ] Item 1
        - [ ] Item 2
    validations:
      required: true
  - type: textarea
    id: resources-instructions
    attributes:
      label: "Resources/Instructions"
      description: "Provide links to resources or instructions that may help with this issue. This can include files to be worked on, external sites with solutions, documentation, etc."
      value: |
        [Resources](https://hackforla.github.io/CivicTechJobs/resources/)
    validations:
      required: true
