# Generated by Django 6.0.4 on 2026-05-08 15:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityOfPractice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('practice_area', models.CharField(choices=[('data_science', 'Data Science'), ('engineering', 'Engineering'), ('devops', 'DevOps'), ('project_management', 'Project/Product Management'), ('ui_ux', 'UI/UX')], max_length=50, unique=True)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Community of Practice',
                'verbose_name_plural': 'Communities of Practice',
                'db_table': 'community_of_practice',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('people_depot_project_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('meeting_times', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='SkillMatrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_matrix', models.JSONField(default=dict, help_text='Skill matrix mapping Skill id to a mastery level (1-5).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Skill Matrix',
                'verbose_name_plural': 'Skill Matrices',
                'db_table': 'skill_matrices',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('community_of_practice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='ctj_api.communityofpractice')),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communities_of_practice', models.ManyToManyField(related_name='skills', to='ctj_api.communityofpractice')),
            ],
            options={
                'db_table': 'skills',
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(help_text='A description of the opportunity.')),
                ('min_experience_required', models.CharField(blank=True, help_text='min_experience_required: junior, senior, mid-level, etc.', max_length=50, null=True)),
                ('min_hours_required', models.IntegerField(help_text='Minimum hours required per week.')),
                ('work_environment', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('in_person', 'In Person')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('on hold', 'On hold'), ('filled', 'Filled'), ('draft', 'Draft')], help_text='Status will determine how the opportunity will be shown publicly.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='For now, only the creator can make changes to the opportunity.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_opportunities', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='ctj_api.project')),
                ('role', models.ForeignKey(help_text='Role.title will be the title of the opportunity.', on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='ctj_api.role')),
                ('skills_required_matrix', models.OneToOneField(blank=True, help_text='A list of required skills mapped to desired skill level (1-5).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunity', to='ctj_api.skillmatrix')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'db_table': 'opportunities',
            },
        ),
    ]
