# Generated by Django 6.0.4 on 2026-06-02, then hand-edited:
# - file renamed for legibility,
# - added a RunPython data step at the front for the `"on hold"` ->
#   `"on_hold"` status rename and the `min_experience_required`
#   NULL -> "" backfill. The RunPython has to come *before* the
#   `AlterField` on `status` (so the new choices validate) and
#   *before* the `AlterField` on `min_experience_required` (the new
#   shape isn't `null=True` anymore; backfilling avoids the
#   NOT-NULL transition tripping on existing NULL rows).
#
# Schema-wise this migration dissolves the `Project` model: the
# `Opportunity.project` FK is removed, the project's `meeting_times`
# JSON moves onto `Opportunity` as a column, and the project name
# becomes the free-text `Opportunity.project_name`. Existing project
# associations are dropped (pre-launch reshape; PeopleDepot owns
# projects upstream). The `overview` / `responsibilities` card text
# also moves onto `Opportunity` (decoupled from `Role`).

from django.db import migrations, models


def _fix_opportunity_data(apps, schema_editor):
    """Forward data migration: rename `"on hold"` status and backfill NULL experience."""
    Opportunity = apps.get_model("ctj_api", "Opportunity")
    Opportunity.objects.filter(status="on hold").update(status="on_hold")
    Opportunity.objects.filter(min_experience_required__isnull=True).update(
        min_experience_required=""
    )


def _revert_opportunity_data(apps, schema_editor):
    """Reverse: put `"on hold"` back. The NULL backfill isn't
    reversible (we can't tell which `""` came from a NULL row), so
    leave those as empty strings on revert.
    """
    Opportunity = apps.get_model("ctj_api", "Opportunity")
    Opportunity.objects.filter(status="on_hold").update(status="on hold")


class Migration(migrations.Migration):

    dependencies = [
        ("ctj_api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(_fix_opportunity_data, _revert_opportunity_data),
        migrations.RemoveField(
            model_name="opportunity",
            name="project",
        ),
        migrations.AddField(
            model_name="opportunity",
            name="project_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text=(
                    "Free-text project name. Not a FK - PeopleDepot owns "
                    "projects upstream. Doubles as the (deliberately weak) "
                    "project filter key."
                ),
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="overview",
            field=models.TextField(
                blank=True,
                default="",
                help_text='Card "Role Overview" section: what this position is and does.',
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="responsibilities",
            field=models.TextField(
                blank=True,
                default="",
                help_text='Card "Responsibilities" section: what is expected of the volunteer.',
            ),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="meeting_times",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="min_experience_required",
            field=models.CharField(
                blank=True,
                default="",
                help_text="min_experience_required: junior, senior, mid-level, etc.",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("on_hold", "On hold"),
                    ("filled", "Filled"),
                    ("draft", "Draft"),
                ],
                default="draft",
                help_text="Status will determine how the opportunity is shown.",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Project",
        ),
    ]
