# Generated by Django 5.1.2 on 2024-12-13 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ctj_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="communityofpractice",
            name="practice_area",
            field=models.CharField(
                choices=[
                    ("data_science", "Data Science"),
                    ("engineering", "Engineering"),
                    ("devops", "DevOps"),
                    ("project_management", "Project/Product Management"),
                    ("ui_ux", "UI/UX"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="isProjectManager",
            field=models.BooleanField(
                default=False,
                help_text="A user that is a PM can create and edit opportunities in the CMS.",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="skills_learned_matrix",
            field=models.OneToOneField(
                blank=True,
                help_text="User's list of skills mapped to a mastery level (1-5).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user",
                to="ctj_api.skillmatrix",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="body",
            field=models.TextField(help_text="A description of the opportunity."),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="For now, only the creator can make changes to the opportunity.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_opportunities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="min_experience_required",
            field=models.CharField(
                blank=True,
                help_text="min_experience_required: junior, senior, mid-level, etc.",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="min_hours_required",
            field=models.IntegerField(help_text="Minimum hours required per week."),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="role",
            field=models.ForeignKey(
                help_text="Role.title will be the title of the opportunity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="opportunities",
                to="ctj_api.role",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="skills_required_matrix",
            field=models.OneToOneField(
                blank=True,
                help_text="A list of required skills mapped to desired skill level (1-5).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="opportunity",
                to="ctj_api.skillmatrix",
            ),
        ),
        migrations.AlterField(
            model_name="opportunity",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("on hold", "On hold"),
                    ("filled", "Filled"),
                    ("draft", "Draft"),
                ],
                help_text="Status will determine how the opportunity will be shown publicly.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="people_depot_project_id",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="skill",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
