name: Issue Trigger
on:
  issues:
    types: [opened]

jobs:
  Sort-Opened-Issue-Into-Columns:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Move Issue
        uses: 100Automations/miniature-octo-sniffle@v0.0.1-alpha
        with:
          # required
          config-file: "./.github/workflows/sortOpenedIssues/config.json"
          myToken: ${{ secrets.GITHUB_TOKEN }}
          # optional
          default-column: 17121475
