version: "3.9"
services:
  mkdocs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mkdocs
    command: mkdocs serve -a "0.0.0.0:3000"
    ports:
      - "3000:3000"
    volumes:
      - .:/code
